name: gate

on:
  pull_request:
  push:
    branches: ["main"]

permissions:
  contents: read

jobs:
  prek-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false

      - name: Install uv
        uses: astral-sh/setup-uv@5a095e7a2014a4212f075830d4f7277575a9d098
        with:
          enable-cache: true

      - name: Install dependencies
        run: uv sync --dev

      - name: Run Prek (pre-commit)
        uses: j178/prek-action@0bb87d7f00b0c99306c8bcb8b8beba1eb581c037
        with:
          extra_args: "--all-files"
        env:
          SKIP: no-commit-to-branch

  services-checks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false

      - name: Install uv
        uses: astral-sh/setup-uv@5a095e7a2014a4212f075830d4f7277575a9d098
        with:
          enable-cache: true

      - name: Install dependencies
        run: uv sync --dev

      - name: Run tests
        env:
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        run: ./scripts/service-test.sh --all

  integration-tests:
    runs-on: ubuntu-latest
    needs:
      - prek-check
      - services-checks

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false

      - name: Install uv
        uses: astral-sh/setup-uv@5a095e7a2014a4212f075830d4f7277575a9d098
        with:
          enable-cache: true

      - name: Install dependencies
        run: uv sync --dev

      - name: Install Pulumi
        uses: pulumi/actions@8582a9e8cc630786854029b4e09281acd6794b58

      - name: Run integration tests
        env:
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          PULUMI_CONFIG_PASSPHRASE: ${{ secrets.PULUMI_CONFIG_PASSPHRASE }}
        working-directory: infrastructure
        run: |
          pulumi login s3://fairbuddy-pulumi-state
          uv run pytest -m integration tests/
